#!/usr/bin/env bash

STORED_SCRIPT_DIR=$1
MAPPINGS_DIR=$2
OPENSEARCH_POLICY_DIR=$3
OPENSEARCH_HOST=$4

./create_scripts.sh $STORED_SCRIPT_DIR $OPENSEARCH_HOST
./create_policies.sh $OPENSEARCH_POLICY_DIR $OPENSEARCH_HOST
./create_indexes.sh $MAPPINGS_DIR $OPENSEARCH_HOST
